### ISSUE TITLE
А по какой причине так преобразуется значение Editor?

### ISSUE THREAD

**Issue by WinterSilence** [execut/yii2-crud-fields#1]
https://github.com/execut/yii2-crud-fields/blob/09361713be798a8f98db36a5aa684f9b2be73265/src/fields/Editor.php#L35

**Comment by execut** [comment]
Приветствую! Я так сделал, чтобы вывести урезанное значение в столбце CRUD-а без html и, чтобы при этом всё в списке ничего не поехало.

**Comment by execut** [comment]
@WinterSilence Есть идея как это реализовать лучше?

**Comment by WinterSilence** [comment]
@execut это не притензия, просто разбираюсь - хотел посмореть реализацию WYSIWYG вопрос, а там на удивление пусто. Не знал что это поле для табличного отображения - у меня этот функционал  выполняет виджет таблицы данных.
